# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from jaco_control/InteractionParams.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class InteractionParams(genpy.Message):
  _md5sum = "51a6ad46b6075e569062a950d4a73881"
  _type = "jaco_control/InteractionParams"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point center
float64 radius
float64 cut_force_k
float64 cut_force_d
geometry_msgs/Vector3 direction
geometry_msgs/Vector3 plane

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['center','radius','cut_force_k','cut_force_d','direction','plane']
  _slot_types = ['geometry_msgs/Point','float64','float64','float64','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       center,radius,cut_force_k,cut_force_d,direction,plane

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(InteractionParams, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.radius is None:
        self.radius = 0.
      if self.cut_force_k is None:
        self.cut_force_k = 0.
      if self.cut_force_d is None:
        self.cut_force_d = 0.
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      if self.plane is None:
        self.plane = geometry_msgs.msg.Vector3()
    else:
      self.center = geometry_msgs.msg.Point()
      self.radius = 0.
      self.cut_force_k = 0.
      self.cut_force_d = 0.
      self.direction = geometry_msgs.msg.Vector3()
      self.plane = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.cut_force_k, _x.cut_force_d, _x.direction.x, _x.direction.y, _x.direction.z, _x.plane.x, _x.plane.y, _x.plane.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      if self.plane is None:
        self.plane = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.cut_force_k, _x.cut_force_d, _x.direction.x, _x.direction.y, _x.direction.z, _x.plane.x, _x.plane.y, _x.plane.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_12d().pack(_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.cut_force_k, _x.cut_force_d, _x.direction.x, _x.direction.y, _x.direction.z, _x.plane.x, _x.plane.y, _x.plane.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.center is None:
        self.center = geometry_msgs.msg.Point()
      if self.direction is None:
        self.direction = geometry_msgs.msg.Vector3()
      if self.plane is None:
        self.plane = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 96
      (_x.center.x, _x.center.y, _x.center.z, _x.radius, _x.cut_force_k, _x.cut_force_d, _x.direction.x, _x.direction.y, _x.direction.z, _x.plane.x, _x.plane.y, _x.plane.z,) = _get_struct_12d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_12d = None
def _get_struct_12d():
    global _struct_12d
    if _struct_12d is None:
        _struct_12d = struct.Struct("<12d")
    return _struct_12d
