// Generated by gencpp from file kinovasev/kinova_jointvelocity.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_JOINTVELOCITY_H
#define KINOVASEV_MESSAGE_KINOVA_JOINTVELOCITY_H

#include <ros/service_traits.h>


#include <kinovasev/kinova_jointvelocityRequest.h>
#include <kinovasev/kinova_jointvelocityResponse.h>


namespace kinovasev
{

struct kinova_jointvelocity
{

typedef kinova_jointvelocityRequest Request;
typedef kinova_jointvelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinova_jointvelocity
} // namespace kinovasev


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinovasev::kinova_jointvelocity > {
  static const char* value()
  {
    return "9d51386228009e7e125e42b13c7f7ff5";
  }

  static const char* value(const ::kinovasev::kinova_jointvelocity&) { return value(); }
};

template<>
struct DataType< ::kinovasev::kinova_jointvelocity > {
  static const char* value()
  {
    return "kinovasev/kinova_jointvelocity";
  }

  static const char* value(const ::kinovasev::kinova_jointvelocity&) { return value(); }
};


// service_traits::MD5Sum< ::kinovasev::kinova_jointvelocityRequest> should match
// service_traits::MD5Sum< ::kinovasev::kinova_jointvelocity >
template<>
struct MD5Sum< ::kinovasev::kinova_jointvelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_jointvelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_jointvelocityRequest> should match
// service_traits::DataType< ::kinovasev::kinova_jointvelocity >
template<>
struct DataType< ::kinovasev::kinova_jointvelocityRequest>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_jointvelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinovasev::kinova_jointvelocityResponse> should match
// service_traits::MD5Sum< ::kinovasev::kinova_jointvelocity >
template<>
struct MD5Sum< ::kinovasev::kinova_jointvelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_jointvelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_jointvelocityResponse> should match
// service_traits::DataType< ::kinovasev::kinova_jointvelocity >
template<>
struct DataType< ::kinovasev::kinova_jointvelocityResponse>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_jointvelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_JOINTVELOCITY_H
