// Generated by gencpp from file kinovasev/kinova_posevalue.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_POSEVALUE_H
#define KINOVASEV_MESSAGE_KINOVA_POSEVALUE_H

#include <ros/service_traits.h>


#include <kinovasev/kinova_posevalueRequest.h>
#include <kinovasev/kinova_posevalueResponse.h>


namespace kinovasev
{

struct kinova_posevalue
{

typedef kinova_posevalueRequest Request;
typedef kinova_posevalueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinova_posevalue
} // namespace kinovasev


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinovasev::kinova_posevalue > {
  static const char* value()
  {
    return "e893863d15a68f0207dff3b2ba094393";
  }

  static const char* value(const ::kinovasev::kinova_posevalue&) { return value(); }
};

template<>
struct DataType< ::kinovasev::kinova_posevalue > {
  static const char* value()
  {
    return "kinovasev/kinova_posevalue";
  }

  static const char* value(const ::kinovasev::kinova_posevalue&) { return value(); }
};


// service_traits::MD5Sum< ::kinovasev::kinova_posevalueRequest> should match
// service_traits::MD5Sum< ::kinovasev::kinova_posevalue >
template<>
struct MD5Sum< ::kinovasev::kinova_posevalueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_posevalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevalueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_posevalueRequest> should match
// service_traits::DataType< ::kinovasev::kinova_posevalue >
template<>
struct DataType< ::kinovasev::kinova_posevalueRequest>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_posevalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevalueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinovasev::kinova_posevalueResponse> should match
// service_traits::MD5Sum< ::kinovasev::kinova_posevalue >
template<>
struct MD5Sum< ::kinovasev::kinova_posevalueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_posevalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevalueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_posevalueResponse> should match
// service_traits::DataType< ::kinovasev::kinova_posevalue >
template<>
struct DataType< ::kinovasev::kinova_posevalueResponse>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_posevalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevalueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_POSEVALUE_H
