// Generated by gencpp from file kinovasev/kinova_posevelocity.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_POSEVELOCITY_H
#define KINOVASEV_MESSAGE_KINOVA_POSEVELOCITY_H

#include <ros/service_traits.h>


#include <kinovasev/kinova_posevelocityRequest.h>
#include <kinovasev/kinova_posevelocityResponse.h>


namespace kinovasev
{

struct kinova_posevelocity
{

typedef kinova_posevelocityRequest Request;
typedef kinova_posevelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinova_posevelocity
} // namespace kinovasev


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinovasev::kinova_posevelocity > {
  static const char* value()
  {
    return "96fa5deefb115b403d86e82cbda4bf34";
  }

  static const char* value(const ::kinovasev::kinova_posevelocity&) { return value(); }
};

template<>
struct DataType< ::kinovasev::kinova_posevelocity > {
  static const char* value()
  {
    return "kinovasev/kinova_posevelocity";
  }

  static const char* value(const ::kinovasev::kinova_posevelocity&) { return value(); }
};


// service_traits::MD5Sum< ::kinovasev::kinova_posevelocityRequest> should match
// service_traits::MD5Sum< ::kinovasev::kinova_posevelocity >
template<>
struct MD5Sum< ::kinovasev::kinova_posevelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_posevelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_posevelocityRequest> should match
// service_traits::DataType< ::kinovasev::kinova_posevelocity >
template<>
struct DataType< ::kinovasev::kinova_posevelocityRequest>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_posevelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinovasev::kinova_posevelocityResponse> should match
// service_traits::MD5Sum< ::kinovasev::kinova_posevelocity >
template<>
struct MD5Sum< ::kinovasev::kinova_posevelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_posevelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_posevelocityResponse> should match
// service_traits::DataType< ::kinovasev::kinova_posevelocity >
template<>
struct DataType< ::kinovasev::kinova_posevelocityResponse>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_posevelocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_posevelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_POSEVELOCITY_H
