// Generated by gencpp from file kinovasev/kinova_wheelchair_poseRequest.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_WHEELCHAIR_POSEREQUEST_H
#define KINOVASEV_MESSAGE_KINOVA_WHEELCHAIR_POSEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinovasev
{
template <class ContainerAllocator>
struct kinova_wheelchair_poseRequest_
{
  typedef kinova_wheelchair_poseRequest_<ContainerAllocator> Type;

  kinova_wheelchair_poseRequest_()
    : linear_x(0.0)
    , theta(0.0)
    , wheel_ms(0)  {
    }
  kinova_wheelchair_poseRequest_(const ContainerAllocator& _alloc)
    : linear_x(0.0)
    , theta(0.0)
    , wheel_ms(0)  {
  (void)_alloc;
    }



   typedef float _linear_x_type;
  _linear_x_type linear_x;

   typedef float _theta_type;
  _theta_type theta;

   typedef int64_t _wheel_ms_type;
  _wheel_ms_type wheel_ms;





  typedef boost::shared_ptr< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kinova_wheelchair_poseRequest_

typedef ::kinovasev::kinova_wheelchair_poseRequest_<std::allocator<void> > kinova_wheelchair_poseRequest;

typedef boost::shared_ptr< ::kinovasev::kinova_wheelchair_poseRequest > kinova_wheelchair_poseRequestPtr;
typedef boost::shared_ptr< ::kinovasev::kinova_wheelchair_poseRequest const> kinova_wheelchair_poseRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator2> & rhs)
{
  return lhs.linear_x == rhs.linear_x &&
    lhs.theta == rhs.theta &&
    lhs.wheel_ms == rhs.wheel_ms;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinovasev

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0f9d2d4c0d1c7a2ae6ef81590e11f475";
  }

  static const char* value(const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0f9d2d4c0d1c7a2aULL;
  static const uint64_t static_value2 = 0xe6ef81590e11f475ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinovasev/kinova_wheelchair_poseRequest";
  }

  static const char* value(const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 linear_x\n"
"float32 theta\n"
"int64 wheel_ms\n"
;
  }

  static const char* value(const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.linear_x);
      stream.next(m.theta);
      stream.next(m.wheel_ms);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinova_wheelchair_poseRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinovasev::kinova_wheelchair_poseRequest_<ContainerAllocator>& v)
  {
    s << indent << "linear_x: ";
    Printer<float>::stream(s, indent + "  ", v.linear_x);
    s << indent << "theta: ";
    Printer<float>::stream(s, indent + "  ", v.theta);
    s << indent << "wheel_ms: ";
    Printer<int64_t>::stream(s, indent + "  ", v.wheel_ms);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_WHEELCHAIR_POSEREQUEST_H
