// Generated by gencpp from file kinovasev/kinova_jointvalue.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_JOINTVALUE_H
#define KINOVASEV_MESSAGE_KINOVA_JOINTVALUE_H

#include <ros/service_traits.h>


#include <kinovasev/kinova_jointvalueRequest.h>
#include <kinovasev/kinova_jointvalueResponse.h>


namespace kinovasev
{

struct kinova_jointvalue
{

typedef kinova_jointvalueRequest Request;
typedef kinova_jointvalueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinova_jointvalue
} // namespace kinovasev


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinovasev::kinova_jointvalue > {
  static const char* value()
  {
    return "6330034618439aeef98f4199475023e1";
  }

  static const char* value(const ::kinovasev::kinova_jointvalue&) { return value(); }
};

template<>
struct DataType< ::kinovasev::kinova_jointvalue > {
  static const char* value()
  {
    return "kinovasev/kinova_jointvalue";
  }

  static const char* value(const ::kinovasev::kinova_jointvalue&) { return value(); }
};


// service_traits::MD5Sum< ::kinovasev::kinova_jointvalueRequest> should match
// service_traits::MD5Sum< ::kinovasev::kinova_jointvalue >
template<>
struct MD5Sum< ::kinovasev::kinova_jointvalueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_jointvalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvalueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_jointvalueRequest> should match
// service_traits::DataType< ::kinovasev::kinova_jointvalue >
template<>
struct DataType< ::kinovasev::kinova_jointvalueRequest>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_jointvalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvalueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinovasev::kinova_jointvalueResponse> should match
// service_traits::MD5Sum< ::kinovasev::kinova_jointvalue >
template<>
struct MD5Sum< ::kinovasev::kinova_jointvalueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_jointvalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvalueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_jointvalueResponse> should match
// service_traits::DataType< ::kinovasev::kinova_jointvalue >
template<>
struct DataType< ::kinovasev::kinova_jointvalueResponse>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_jointvalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_jointvalueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_JOINTVALUE_H
