// Generated by gencpp from file kinovasev/kinova_jointvelocityResponse.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_JOINTVELOCITYRESPONSE_H
#define KINOVASEV_MESSAGE_KINOVA_JOINTVELOCITYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinovasev
{
template <class ContainerAllocator>
struct kinova_jointvelocityResponse_
{
  typedef kinova_jointvelocityResponse_<ContainerAllocator> Type;

  kinova_jointvelocityResponse_()
    : joint_velocity_result(false)  {
    }
  kinova_jointvelocityResponse_(const ContainerAllocator& _alloc)
    : joint_velocity_result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _joint_velocity_result_type;
  _joint_velocity_result_type joint_velocity_result;





  typedef boost::shared_ptr< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kinova_jointvelocityResponse_

typedef ::kinovasev::kinova_jointvelocityResponse_<std::allocator<void> > kinova_jointvelocityResponse;

typedef boost::shared_ptr< ::kinovasev::kinova_jointvelocityResponse > kinova_jointvelocityResponsePtr;
typedef boost::shared_ptr< ::kinovasev::kinova_jointvelocityResponse const> kinova_jointvelocityResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint_velocity_result == rhs.joint_velocity_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinovasev

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "af8d88d0581987cec1798b5f35f1878c";
  }

  static const char* value(const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xaf8d88d0581987ceULL;
  static const uint64_t static_value2 = 0xc1798b5f35f1878cULL;
};

template<class ContainerAllocator>
struct DataType< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinovasev/kinova_jointvelocityResponse";
  }

  static const char* value(const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool joint_velocity_result\n"
;
  }

  static const char* value(const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_velocity_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinova_jointvelocityResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinovasev::kinova_jointvelocityResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_velocity_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joint_velocity_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_JOINTVELOCITYRESPONSE_H
