// Generated by gencpp from file kinovasev/kinova_posevalueResponse.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_POSEVALUERESPONSE_H
#define KINOVASEV_MESSAGE_KINOVA_POSEVALUERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinovasev
{
template <class ContainerAllocator>
struct kinova_posevalueResponse_
{
  typedef kinova_posevalueResponse_<ContainerAllocator> Type;

  kinova_posevalueResponse_()
    : pose_control_result(false)  {
    }
  kinova_posevalueResponse_(const ContainerAllocator& _alloc)
    : pose_control_result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _pose_control_result_type;
  _pose_control_result_type pose_control_result;





  typedef boost::shared_ptr< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kinova_posevalueResponse_

typedef ::kinovasev::kinova_posevalueResponse_<std::allocator<void> > kinova_posevalueResponse;

typedef boost::shared_ptr< ::kinovasev::kinova_posevalueResponse > kinova_posevalueResponsePtr;
typedef boost::shared_ptr< ::kinovasev::kinova_posevalueResponse const> kinova_posevalueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.pose_control_result == rhs.pose_control_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinovasev

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bca241d26520b6469084355b1783b41";
  }

  static const char* value(const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bca241d26520b64ULL;
  static const uint64_t static_value2 = 0x69084355b1783b41ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinovasev/kinova_posevalueResponse";
  }

  static const char* value(const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool pose_control_result\n"
;
  }

  static const char* value(const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_control_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinova_posevalueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinovasev::kinova_posevalueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinovasev::kinova_posevalueResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose_control_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pose_control_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_POSEVALUERESPONSE_H
