// Generated by gencpp from file kinovasev/kinova_posevalueRequest.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_POSEVALUEREQUEST_H
#define KINOVASEV_MESSAGE_KINOVA_POSEVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinovasev
{
template <class ContainerAllocator>
struct kinova_posevalueRequest_
{
  typedef kinova_posevalueRequest_<ContainerAllocator> Type;

  kinova_posevalueRequest_()
    : unit()
    , pose_value()
    , relative_(false)  {
    }
  kinova_posevalueRequest_(const ContainerAllocator& _alloc)
    : unit(_alloc)
    , pose_value(_alloc)
    , relative_(false)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _unit_type;
  _unit_type unit;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _pose_value_type;
  _pose_value_type pose_value;

   typedef uint8_t _relative__type;
  _relative__type relative_;





  typedef boost::shared_ptr< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kinova_posevalueRequest_

typedef ::kinovasev::kinova_posevalueRequest_<std::allocator<void> > kinova_posevalueRequest;

typedef boost::shared_ptr< ::kinovasev::kinova_posevalueRequest > kinova_posevalueRequestPtr;
typedef boost::shared_ptr< ::kinovasev::kinova_posevalueRequest const> kinova_posevalueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.unit == rhs.unit &&
    lhs.pose_value == rhs.pose_value &&
    lhs.relative_ == rhs.relative_;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinovasev

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57936cf6845123c96d5dda05ee9dc6ee";
  }

  static const char* value(const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57936cf6845123c9ULL;
  static const uint64_t static_value2 = 0x6d5dda05ee9dc6eeULL;
};

template<class ContainerAllocator>
struct DataType< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinovasev/kinova_posevalueRequest";
  }

  static const char* value(const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string unit\n"
"float32[] pose_value\n"
"bool relative_\n"
;
  }

  static const char* value(const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.unit);
      stream.next(m.pose_value);
      stream.next(m.relative_);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinova_posevalueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinovasev::kinova_posevalueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinovasev::kinova_posevalueRequest_<ContainerAllocator>& v)
  {
    s << indent << "unit: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.unit);
    s << indent << "pose_value[]" << std::endl;
    for (size_t i = 0; i < v.pose_value.size(); ++i)
    {
      s << indent << "  pose_value[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.pose_value[i]);
    }
    s << indent << "relative_: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.relative_);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_POSEVALUEREQUEST_H
