// Generated by gencpp from file kinovasev/kinova_fingervalueResponse.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_FINGERVALUERESPONSE_H
#define KINOVASEV_MESSAGE_KINOVA_FINGERVALUERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinovasev
{
template <class ContainerAllocator>
struct kinova_fingervalueResponse_
{
  typedef kinova_fingervalueResponse_<ContainerAllocator> Type;

  kinova_fingervalueResponse_()
    : finger_control_result(false)  {
    }
  kinova_fingervalueResponse_(const ContainerAllocator& _alloc)
    : finger_control_result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _finger_control_result_type;
  _finger_control_result_type finger_control_result;





  typedef boost::shared_ptr< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kinova_fingervalueResponse_

typedef ::kinovasev::kinova_fingervalueResponse_<std::allocator<void> > kinova_fingervalueResponse;

typedef boost::shared_ptr< ::kinovasev::kinova_fingervalueResponse > kinova_fingervalueResponsePtr;
typedef boost::shared_ptr< ::kinovasev::kinova_fingervalueResponse const> kinova_fingervalueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.finger_control_result == rhs.finger_control_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinovasev

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "262812f1a2440c1786eb6135f1000b3c";
  }

  static const char* value(const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x262812f1a2440c17ULL;
  static const uint64_t static_value2 = 0x86eb6135f1000b3cULL;
};

template<class ContainerAllocator>
struct DataType< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinovasev/kinova_fingervalueResponse";
  }

  static const char* value(const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool finger_control_result\n"
;
  }

  static const char* value(const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finger_control_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinova_fingervalueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinovasev::kinova_fingervalueResponse_<ContainerAllocator>& v)
  {
    s << indent << "finger_control_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.finger_control_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_FINGERVALUERESPONSE_H
