// Generated by gencpp from file kinovasev/kinova_fingervalue.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_FINGERVALUE_H
#define KINOVASEV_MESSAGE_KINOVA_FINGERVALUE_H

#include <ros/service_traits.h>


#include <kinovasev/kinova_fingervalueRequest.h>
#include <kinovasev/kinova_fingervalueResponse.h>


namespace kinovasev
{

struct kinova_fingervalue
{

typedef kinova_fingervalueRequest Request;
typedef kinova_fingervalueResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinova_fingervalue
} // namespace kinovasev


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinovasev::kinova_fingervalue > {
  static const char* value()
  {
    return "80b4b1c7ca93496e230bb138b990fbaa";
  }

  static const char* value(const ::kinovasev::kinova_fingervalue&) { return value(); }
};

template<>
struct DataType< ::kinovasev::kinova_fingervalue > {
  static const char* value()
  {
    return "kinovasev/kinova_fingervalue";
  }

  static const char* value(const ::kinovasev::kinova_fingervalue&) { return value(); }
};


// service_traits::MD5Sum< ::kinovasev::kinova_fingervalueRequest> should match
// service_traits::MD5Sum< ::kinovasev::kinova_fingervalue >
template<>
struct MD5Sum< ::kinovasev::kinova_fingervalueRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_fingervalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_fingervalueRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_fingervalueRequest> should match
// service_traits::DataType< ::kinovasev::kinova_fingervalue >
template<>
struct DataType< ::kinovasev::kinova_fingervalueRequest>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_fingervalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_fingervalueRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinovasev::kinova_fingervalueResponse> should match
// service_traits::MD5Sum< ::kinovasev::kinova_fingervalue >
template<>
struct MD5Sum< ::kinovasev::kinova_fingervalueResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_fingervalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_fingervalueResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_fingervalueResponse> should match
// service_traits::DataType< ::kinovasev::kinova_fingervalue >
template<>
struct DataType< ::kinovasev::kinova_fingervalueResponse>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_fingervalue >::value();
  }
  static const char* value(const ::kinovasev::kinova_fingervalueResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_FINGERVALUE_H
