// Generated by gencpp from file kinovasev/kinova_jointvalueResponse.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_JOINTVALUERESPONSE_H
#define KINOVASEV_MESSAGE_KINOVA_JOINTVALUERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinovasev
{
template <class ContainerAllocator>
struct kinova_jointvalueResponse_
{
  typedef kinova_jointvalueResponse_<ContainerAllocator> Type;

  kinova_jointvalueResponse_()
    : joint_control_result(false)  {
    }
  kinova_jointvalueResponse_(const ContainerAllocator& _alloc)
    : joint_control_result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _joint_control_result_type;
  _joint_control_result_type joint_control_result;





  typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> const> ConstPtr;

}; // struct kinova_jointvalueResponse_

typedef ::kinovasev::kinova_jointvalueResponse_<std::allocator<void> > kinova_jointvalueResponse;

typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueResponse > kinova_jointvalueResponsePtr;
typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueResponse const> kinova_jointvalueResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator2> & rhs)
{
  return lhs.joint_control_result == rhs.joint_control_result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinovasev

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3e25815b10fd5e4a9881542c04bf1b1b";
  }

  static const char* value(const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3e25815b10fd5e4aULL;
  static const uint64_t static_value2 = 0x9881542c04bf1b1bULL;
};

template<class ContainerAllocator>
struct DataType< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinovasev/kinova_jointvalueResponse";
  }

  static const char* value(const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool joint_control_result\n"
;
  }

  static const char* value(const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_control_result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinova_jointvalueResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinovasev::kinova_jointvalueResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_control_result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joint_control_result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_JOINTVALUERESPONSE_H
