// Generated by gencpp from file kinovasev/kinova_wheelchair_velocity.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_WHEELCHAIR_VELOCITY_H
#define KINOVASEV_MESSAGE_KINOVA_WHEELCHAIR_VELOCITY_H

#include <ros/service_traits.h>


#include <kinovasev/kinova_wheelchair_velocityRequest.h>
#include <kinovasev/kinova_wheelchair_velocityResponse.h>


namespace kinovasev
{

struct kinova_wheelchair_velocity
{

typedef kinova_wheelchair_velocityRequest Request;
typedef kinova_wheelchair_velocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct kinova_wheelchair_velocity
} // namespace kinovasev


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kinovasev::kinova_wheelchair_velocity > {
  static const char* value()
  {
    return "1404a3850413496a35cd6eb1f5887dd3";
  }

  static const char* value(const ::kinovasev::kinova_wheelchair_velocity&) { return value(); }
};

template<>
struct DataType< ::kinovasev::kinova_wheelchair_velocity > {
  static const char* value()
  {
    return "kinovasev/kinova_wheelchair_velocity";
  }

  static const char* value(const ::kinovasev::kinova_wheelchair_velocity&) { return value(); }
};


// service_traits::MD5Sum< ::kinovasev::kinova_wheelchair_velocityRequest> should match
// service_traits::MD5Sum< ::kinovasev::kinova_wheelchair_velocity >
template<>
struct MD5Sum< ::kinovasev::kinova_wheelchair_velocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_wheelchair_velocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_wheelchair_velocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_wheelchair_velocityRequest> should match
// service_traits::DataType< ::kinovasev::kinova_wheelchair_velocity >
template<>
struct DataType< ::kinovasev::kinova_wheelchair_velocityRequest>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_wheelchair_velocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_wheelchair_velocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kinovasev::kinova_wheelchair_velocityResponse> should match
// service_traits::MD5Sum< ::kinovasev::kinova_wheelchair_velocity >
template<>
struct MD5Sum< ::kinovasev::kinova_wheelchair_velocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kinovasev::kinova_wheelchair_velocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_wheelchair_velocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kinovasev::kinova_wheelchair_velocityResponse> should match
// service_traits::DataType< ::kinovasev::kinova_wheelchair_velocity >
template<>
struct DataType< ::kinovasev::kinova_wheelchair_velocityResponse>
{
  static const char* value()
  {
    return DataType< ::kinovasev::kinova_wheelchair_velocity >::value();
  }
  static const char* value(const ::kinovasev::kinova_wheelchair_velocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_WHEELCHAIR_VELOCITY_H
