// Generated by gencpp from file kinovasev/kinova_jointvalueRequest.msg
// DO NOT EDIT!


#ifndef KINOVASEV_MESSAGE_KINOVA_JOINTVALUEREQUEST_H
#define KINOVASEV_MESSAGE_KINOVA_JOINTVALUEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace kinovasev
{
template <class ContainerAllocator>
struct kinova_jointvalueRequest_
{
  typedef kinova_jointvalueRequest_<ContainerAllocator> Type;

  kinova_jointvalueRequest_()
    : joint_control_mode()
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)
    , joint7(0.0)  {
    }
  kinova_jointvalueRequest_(const ContainerAllocator& _alloc)
    : joint_control_mode(_alloc)
    , joint1(0.0)
    , joint2(0.0)
    , joint3(0.0)
    , joint4(0.0)
    , joint5(0.0)
    , joint6(0.0)
    , joint7(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _joint_control_mode_type;
  _joint_control_mode_type joint_control_mode;

   typedef float _joint1_type;
  _joint1_type joint1;

   typedef float _joint2_type;
  _joint2_type joint2;

   typedef float _joint3_type;
  _joint3_type joint3;

   typedef float _joint4_type;
  _joint4_type joint4;

   typedef float _joint5_type;
  _joint5_type joint5;

   typedef float _joint6_type;
  _joint6_type joint6;

   typedef float _joint7_type;
  _joint7_type joint7;





  typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> const> ConstPtr;

}; // struct kinova_jointvalueRequest_

typedef ::kinovasev::kinova_jointvalueRequest_<std::allocator<void> > kinova_jointvalueRequest;

typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueRequest > kinova_jointvalueRequestPtr;
typedef boost::shared_ptr< ::kinovasev::kinova_jointvalueRequest const> kinova_jointvalueRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator2> & rhs)
{
  return lhs.joint_control_mode == rhs.joint_control_mode &&
    lhs.joint1 == rhs.joint1 &&
    lhs.joint2 == rhs.joint2 &&
    lhs.joint3 == rhs.joint3 &&
    lhs.joint4 == rhs.joint4 &&
    lhs.joint5 == rhs.joint5 &&
    lhs.joint6 == rhs.joint6 &&
    lhs.joint7 == rhs.joint7;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator1> & lhs, const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace kinovasev

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0005b62bc9e5dfcd1cb29f7364c90f32";
  }

  static const char* value(const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0005b62bc9e5dfcdULL;
  static const uint64_t static_value2 = 0x1cb29f7364c90f32ULL;
};

template<class ContainerAllocator>
struct DataType< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "kinovasev/kinova_jointvalueRequest";
  }

  static const char* value(const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string joint_control_mode\n"
"float32 joint1\n"
"float32 joint2\n"
"float32 joint3\n"
"float32 joint4\n"
"float32 joint5\n"
"float32 joint6\n"
"float32 joint7\n"
;
  }

  static const char* value(const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_control_mode);
      stream.next(m.joint1);
      stream.next(m.joint2);
      stream.next(m.joint3);
      stream.next(m.joint4);
      stream.next(m.joint5);
      stream.next(m.joint6);
      stream.next(m.joint7);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct kinova_jointvalueRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::kinovasev::kinova_jointvalueRequest_<ContainerAllocator>& v)
  {
    s << indent << "joint_control_mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.joint_control_mode);
    s << indent << "joint1: ";
    Printer<float>::stream(s, indent + "  ", v.joint1);
    s << indent << "joint2: ";
    Printer<float>::stream(s, indent + "  ", v.joint2);
    s << indent << "joint3: ";
    Printer<float>::stream(s, indent + "  ", v.joint3);
    s << indent << "joint4: ";
    Printer<float>::stream(s, indent + "  ", v.joint4);
    s << indent << "joint5: ";
    Printer<float>::stream(s, indent + "  ", v.joint5);
    s << indent << "joint6: ";
    Printer<float>::stream(s, indent + "  ", v.joint6);
    s << indent << "joint7: ";
    Printer<float>::stream(s, indent + "  ", v.joint7);
  }
};

} // namespace message_operations
} // namespace ros

#endif // KINOVASEV_MESSAGE_KINOVA_JOINTVALUEREQUEST_H
